config/routes.rb
Rails.application.routes.draw do
  devise_for :users, {
    sessions: 'users/sessions'
  }

  resources :passwords
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'passwords#index'
  namespace :admin do
    resources :groups
    resources :memberships
    resources :permissions
    resources :roles
    resources :users
  end
  # resources :roles
  # resources :groups
  # resources :permissions
  # resources :users
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/_form.html.erb
<%= form_with(model: role, local: true) do |form| %>
  <% if role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
      <% role.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :group_id %>
    <%= form.number_field :group_id %>
  </div>

  <div class="field">
    <%= form.label :permission_id %>
    <%= form.number_field :permission_id %>
  </div>

  <div class="field">
    <%= form.label :role_id %>
    <%= form.number_field :role_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/roles/edit.html.erb
<h1>Editing Role</h1>

<%= render 'form', role: @role %>

<%= link_to 'Show', @role %> |
<%= link_to 'Back', roles_path %>

app/views/roles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Roles</h1>

<table>
  <thead>
    <tr>
      <th>Group</th>
      <th>Permission</th>
      <th>Role</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @roles.each do |role| %>
      <tr>
        <td><%= role.group_id %></td>
        <td><%= role.permission_id %></td>
        <td><%= role.role_id %></td>
        <td><%= link_to 'Show', role %></td>
        <td><%= link_to 'Edit', edit_role_path(role) %></td>
        <td><%= link_to 'Destroy', role, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Role', new_role_path %>

app/views/roles/new.html.erb
<h1>New Role</h1>

<%= render 'form', role: @role %>

<%= link_to 'Back', roles_path %>

app/views/roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Group:</strong>
  <%= @role.group_id %>
</p>

<p>
  <strong>Permission:</strong>
  <%= @role.permission_id %>
</p>

<p>
  <strong>Role:</strong>
  <%= @role.role_id %>
</p>

<%= link_to 'Edit', edit_role_path(@role) %> |
<%= link_to 'Back', roles_path %>